# Generated by Django 4.2.23 on 2025-08-21 12:14

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_tour'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='end_date',
            field=models.DateField(default=users.models.default_end_date),
        ),
        migrations.AddField(
            model_name='tour',
            name='start_date',
            field=models.DateField(default=users.models.default_start_date),
        ),
        migrations.AddField(
            model_name='tour',
            name='visa_required',
            field=models.BooleanField(default=False, help_text='Check if visa is required for this destination'),
        ),
    ]
