# Generated by Django 4.2.23 on 2025-08-21 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_tour_end_date_tour_start_date_tour_visa_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='meal_plan',
            field=models.CharField(choices=[('room_only', 'Room Only'), ('bed_breakfast', 'Bed & Breakfast'), ('half_board', 'Half Board'), ('full_board', 'Full Board'), ('all_inclusive', 'All Inclusive')], default='room_only', help_text='Meal plan included in the tour package', max_length=20),
        ),
    ]
