# Generated by Django 4.2.23 on 2025-08-21 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_tour_meal_plan'),
    ]

    operations = [
        migrations.CreateModel(
            name='TourCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('website', models.URLField(blank=True)),
                ('license_number', models.CharField(blank=True, help_text='Tour operator license number', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Tour Companies',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='tour_company',
            field=models.ForeignKey(blank=True, help_text='Tour company this agent belongs to (only for agents)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agents', to='users.tourcompany'),
        ),
    ]
