# Generated by Django 4.2.23 on 2025-08-21 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_tourcompany_user_tour_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tourcompany',
            name='license_number',
        ),
    ]
