# Generated by Django 4.2.23 on 2025-08-21 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_tourcompany_license_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='flight_type',
            field=models.CharField(choices=[('direct', 'Direct Flight'), ('layover', 'Flight with Layover')], default='direct', help_text='Type of flight included in the tour', max_length=20),
        ),
    ]
