# Generated by Django 4.2.23 on 2025-08-21 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_tour_flight_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='hotel_name',
            field=models.CharField(blank=True, help_text='Name of the hotel included in the tour', max_length=200),
        ),
    ]
