# Generated by Django 4.2.23 on 2025-08-21 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_tour_hotel_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='category',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='duration',
        ),
    ]
